### PR TITLE
 Upgrade to Bybit's v5 APIs (5.0.0)

### LINKED ISSUE #15: Wrong Endpoint for Spot Get Active Order
The endpoint for this function should be `/spot/v1/order` instead of `/spot/v1/history-orders`

https://github.com/bybit-exchange/pybit/blob/master/pybit/spot.py#L194

For the general HTTP class, it allows passing in an endpoint that could override this behavior. However, for the spot.HTTP class, there is no endpoint override.

### LINKED ISSUE #62: Websocket usdt_perpetual stream disconnects and can't reconnect
Hello,

I'm using the usdt_perpetual module to stream Bybit klines.
It works fine for a few hours, but then disconnects.
I enabled `trace_logging=True`, and it doesn't seem to be able to reconnect. Here are the logs :

```
++Rcv raw: b'\x81~\x01\x1b{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850641934}],"timestamp_e6":1662243850641934}'
++Rcv decoded: fin=1 opcode=1 data=b'{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850641934}],"timestamp_e6":1662243850641934}'
++Rcv raw: b'\x81~\x01\x1b{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850644262}],"timestamp_e6":1662243850644262}'
++Rcv decoded: fin=1 opcode=1 data=b'{"topic":"candle.5.AXSUSDT","data":[{"start":1662243600,"end":1662243900,"period":"5","open":15.29,"close":15.22,"high":15.325,"low":15.205,"volume":"935.2","turnover":"14273.646","confirm":false,"cross_seq":15485606634,"timestamp":1662243850644262}],"timestamp_e6":1662243850644262}'
++Sent raw: b'\x89\x80\xad\x07\x9c2'
++Sent decoded: fin=1 opcode=9 data=b''
WebSocket USDT Perp encountered error: ping/pong timed out.
++Sent raw: b'\x88\x82\xec\xf1\x0f\x85\xef\x19'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
++Sent raw: b'\x81\xb1\xf2\xc9\x9e\xfa\x89\xeb\xf1\x8a\xd0\xf3\xbe\xd8\x81\xbc\xfc\x89\x91\xbb\xf7\x98\x97\xeb\xb2\xda\xd0\xa8\xec\x9d\x81\xeb\xa4\xda\xa9\xeb\xfd\x9b\x9c\xad\xf2\x9f\xdc\xfc\xb0\xbb\xaa\x9a\xcb\xa9\xb6\x9d\xbc\xa7\x8f'
++Sent decoded: fin=1 opcode=1 data=b'{"op": "subscribe", "args": ["candle.5.AXSUSDT"]}'
error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x00000222BF23CC10>: socket is already closed.
WebSocket USDT Perp encountered error: socket is already closed..
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: HF5PXGToDNRnc7JCO3ZDUQ==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
websocket disconnected (retrying in 5 seconds) [7 frames in stack]
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: jVFinKapUVFnjs3B0R5fx5dZoF4=
Expires: Sat, 03 Sep 2022 22:24:55 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:24:55 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
websocket disconnected (retrying in 5 seconds) [7 frames in stack]
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: ZMMWFVzHAzUmatblWoXGKw==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
--- request header ---
GET /realtime_public HTTP/1.1
Upgrade: websocket
Host: stream-testnet.bybit.com
Origin: https://stream-testnet.bybit.com
Sec-WebSocket-Key: GIlYLnCLUGZCaI5hROrnPw==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: 2P12LiCY939ONnncphWCe5Bm4Ug=
Expires: Sat, 03 Sep 2022 22:25:00 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:25:00 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: MMXg+w5KwECRxBzcWxYP+n66txY=
Expires: Sat, 03 Sep 2022 22:25:01 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 03 Sep 2022 22:25:01 GMT
Upgrade: websocket
Connection: Upgrade
-----------------------
websocket connected
++Sent raw: b'\x89\x80\x9f\x89H\x84'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xe0\xe6\x15\x9f'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\x91\x8f\xf3\xfc'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\x8e\xb5\xf3\x91'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80~\xccC`'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xd4A\xa3\xc3'
++Sent decoded: fin=1 opcode=9 data=b''
++Sent raw: b'\x89\x80\xa7|\nX'
++Sent decoded: fin=1 opcode=9 data=b''
```

In the first lines, the stream still worked. Then it seems to disconnect, and I haven't received any new values from the stream since. At the end, the last lines ("Sent raw" and "Sent decoded") repeat indefinitely.

I am able to detect a lack of new values, indicating a stream disconnection. I tried some methods to relaunch the stream when I detect this disconnection, but they didn't work.

Thanks for your help !

### LINKED ISSUE #78: query symbol info by sybmol
i want to know specific info like the min trade quantity of a symbol but i have to do a for loop to get to the symbol then i can look for the min quantity 

do you guys plan on allowing us to send the symbol as a parameter ... doesn't seem like it should be necessary to for loop to get the info of a symbol

min_trading_qty = 0
for i in pybit_bybit_test_ex.query_symbol()['result']:
	if i['name'] == tradingPair_pybit:
		min_trading_qty = i['lot_size_filter']['min_trading_qty']

i should just be able to do 
pybit_bybit_test_ex.query_symbol(tradingPair_pybit)['lot_size_filter']['min_trading_qty']

### LINKED ISSUE #86: Spot websocket kline_v2_stream
Hey, 

i am getting error on kline v2 1 minute subscription for multiple symbols 

```
 raise Exception("Spot subscription failed.")
Exception: Spot subscription failed.
```

```py
 self.ws_spot.kline_v2_stream(callback=self.process_candles, symbol=["BTCUSDT", "ETHUSDT"], interval='1m')
 ```

for one symbol as string and not list works OK

Thank you for help.

### LINKED ISSUE #92: Upgrade to V5 endpoints
Based on https://bybit-exchange.github.io/docs-v2/v5/intro

### LINKED ISSUE #102: pybit.unfied_trading is not found
Trying to make use of the V5 API, but I cannot figure out how to implement the above ^
I have the latest version of pybit 2.4.1, something I am missing?

### PR DESCRIPTION
**Pull request by dextertd**
Reviews the contribution of #93 and brings them into master. Supersedes #85 (v3 can be seen as a stepping stone towards v5).

### CODE REVIEW

**Comment by dextertd** [comment]
WIP, merge next week. Mostly just websocket review plus updating documentation to come.

**Comment by dextertd** [comment]
@ervuks As you made a huge contribution towards bringing v5 to pybit, very happy to hear your comments or suggested changes on any commits I've made here.

**Comment by dextertd** [comment]
Just realised that this is the 100th issue... Very fitting!

**Comment by ervuks** [comment]
Looks great. 
The only thing I would suggest is to move from legacy [setuptools](https://github.com/bybit-exchange/pybit/pull/100/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)

**Pull request merged**
