### PR TITLE
Update websocket_stream.py to handle field extraction

### PR DESCRIPTION
**Pull request by chanonong**
Update websocket_stream.py to handle field extraction for cases that re.search return None

### CODE REVIEW

**Comment by dextertd** [comment]
Why is this change needed? Can you provide some sample code which triggers the problem please?

**Comment by dextertd** [comment]
Why is this change needed? Can you provide some sample code which triggers the problem please?

**Comment by chanonong** [comment]
After some investigation, I think it's just an error on my part. I apologize for the trouble caused. the regex should cover all normal cases supported by ByBit api

**Comment by dextertd** [comment]
No worries :)

**Pull request closed without merging**
