### PR TITLE
Upgrade to Bybit's v3 APIs (3.0.0)

### PR DESCRIPTION
**Pull request by dextertd**

### CODE REVIEW

**Comment by dextertd** [comment]
This is a work in progress and will not be merged imminently.

**Comment by dextertd** [comment]
Closes #77

**Comment by ervuks** [comment]
@dextertd WDYT, should API reference URL's be included in the codebase as well? 
Are there any topics where help would be needed?

**Comment by dextertd** [comment]
@ervuks Yes links to the API docs should be included in the docstring of each method *but* Bybit's API docs will imminently be moving to a new address so it would be wasted work to add the existing doc URLs (they might not all redirect properly).

I'm currently working on adding copy trading. If you want to help with other topics, one thing would be to help update the [example files for v3](https://github.com/bybit-exchange/pybit/tree/v3/examples), my limited time means I have been focusing on implementing the APIs/WS rather than documenting them properly.

Pybit examples will be added to Bybit's new documentation in any case, but fixing the examples in the repo won't hurt.

**Comment by ervuks** [comment]
Is the webhook part finished already? 
Tried to make some examples, but ran into different problems with domain/topics.

**Comment by dextertd** [comment]
> Is the webhook part finished already? Tried to make some examples, but ran into different problems with domain/topics.

Presuming you mean websocket part, yes it should work for all the modules. Can you share the specific errors here please?

**Comment by ervuks** [comment]
```
mar = unified_margin.WebSocket(
    testnet=True,
    api_key="...",  
    api_secret="...",
)

mar.orderbook_stream(
    callback=handle_orderbook,
    symbol="BTCUSDT",
    level="100"
)
```
Those are parts from the error message: 
```
Couldn't subscribe to topic.Error: error:handler not found,topic:orderbook.100.BTCUSDT.
Exception in thread Thread-1 (<lambda>):
```

```
  File "/Users/epatmalnieks/git/crypto/pybit/pybit/_websocket_stream.py", line 460, in _extract_topic
    return topic_without_symbol[0]
TypeError: 'NoneType' object is not subscriptable
^CTraceback (most recent call last):
  File "/Users/epatmalnieks/git/crypto/pybit/test_file.py", line 40, in <module>
    sleep(1)
```

**Comment by ervuks** [comment]
@dextertd I just found out that there's Bybit V5 API available. 
Perhaps it would be worth to directly upgrade to latest one?

**Comment by dextertd** [comment]
Merging this as it is really the latest main version of pybit. However, upgrade to v5 is imminent, and will soon supersede v3. The latest pybit version is 3.0.0rc5, and the first version of v5 will be 5.0.0rc0 (stay in line with Bybit's API, which doesn't have a v4).

**Pull request merged**
